apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: core.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: backends.core.kubeform.com
spec:
  group: core.kubeform.com
  names:
    kind: Backend
    listKind: BackendList
    plural: backends
    singular: backend
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              gcp:
                properties:
                  bucket:
                    type: string
                  credentials:
                    type: string
                required:
                - bucket
                - credentials
                type: object
              s3:
                properties:
                  accessKey:
                    type: string
                  bucket:
                    type: string
                  key:
                    type: string
                  region:
                    type: string
                  secretKey:
                    type: string
                required:
                - accessKey
                - bucket
                - key
                - region
                - secretKey
                type: object
            type: object
          status:
            properties:
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
